# Generated by Django 2.2.19 on 2021-03-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('sortOrder', models.IntegerField(default=0)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'lkupRole',
                'ordering': ['sortOrder'],
            },
        ),
    ]
